### ISSUE TITLE
Cannot find module 'glob'

### ISSUE THREAD

**Issue by gmarziou** [deepu105/generator-jhipster-entity-audit#1]
Hi Deepu,

When I run `yo jhipster-entity-audit`, I get an error:
     Error: Cannot find module 'glob'

node -v
v4.2.3

I solved it by `npm install -g glob`, maybe a dep is missing in package.json

**Comment by deepu105** [comment]
Thats strange, glob is defined in the package.json anyway ill take a look

**Comment by deepu105** [comment]
Ok glob should be in the dependencies and not dev dependencies, have updated it

**Comment by deepu105** [comment]
closed via https://github.com/deepu105/generator-jhipster-entity-audit/commit/bb90bfa2b69fe8b05f6241c3f5c0519484777657
