### ISSUE TITLE
TypeError: jhipsterFunc.copyTemplate is not a function

### ISSUE THREAD

**Issue by gmarziou** [deepu105/generator-jhipster-entity-audit#3]
I get this error when running the module.

~~~bash
yo jhipster-entity-audit
Composing JHipster configuration with module entity-audit
Welcome to the JHipster Entity Audit Generator! v0.1.6

? Do you want to enable audit for all existing entities? Yes, update all
? Do you want to add an audit log page for entities? Yes

Could not register as a post entity creation hook
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.copyTemplate is not a function
    at module.exports.yeoman.generators.Base.extend.writing (/home/gael/.nvm/versions/node/v4.2.3/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:123:18)
    at /home/gael/.nvm/versions/node/v4.2.3/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
~~~

**Comment by gmarziou** [comment]
My env:

node -v ; yo --version
v4.2.3
1.5.1

**Comment by deepu105** [comment]
Did you npm link the module-hook branch of jhipster from my fork, coz these
functions are not available in the jhipster master yet? My PR is still not
merged

**Comment by deepu105** [comment]
@gmarziou plz do confirm if it was link issue

**Comment by gmarziou** [comment]
No I did not link, I'll try and let you know.

**Comment by gmarziou** [comment]
OK, it works now.

**Comment by sanitar4eg** [comment]
I have the same problem, and your generator does not work
If you can answer here, too http://stackoverflow.com/questions/34900402/jhipster-entity-audit-threw-exception-when-i-try-enable-audit please

**Comment by pascalgrimaud** [comment]
> I trying download generator-jhipster from this repo

:warning: you used [the deepu's repo](https://github.com/deepu105/generator-jhipster) which is not up-to-date !

2 solutions :
- use the [official repo](https://github.com/jhipster/generator-jhipster)
- or, install directly the latest version 2.27.0 of [generator-jhipster](https://www.npmjs.com/package/generator-jhipster)

**Comment by deepu105** [comment]
@pascalgrimaud thanks man, you always beat me to answer this :joy: 
@sanitar4eg please do not cross post everywhere, open issues here and general questions on SO

This error is definitely is when using entity audit with an older Jhipster version.

Make sure you have Jhipster 2.27 installed and also ensure you do `npm unlink` on any jhipster local fork/clone on your file system

Also use entity-audit v 1.0.6 which is the latest

**Comment by pascalgrimaud** [comment]
hehe, np @deepu105, we're a team, we help each other :+1:

**Comment by deepu105** [comment]
Awesome :)
