### ISSUE TITLE
TypeError: jhipsterFunc.copyTemplate is not a function

### ISSUE THREAD

**Issue by srinisubra** [deepu105/generator-jhipster-entity-audit#5]
vagrant@vagrant-ubuntu-trusty-64:~/git/latest$ yo jhipster-entity-audit
Composing JHipster configuration with module entity-audit
Welcome to the JHipster Entity Audit Generator! v1.0.0

? Do you want to enable audit for all existing entities? Yes, update all
? Do you want to add an audit log page for entities? Yes
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.copyTemplate is not a function
    at null.<anonymous> (/usr/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:127:24)
    at Array.forEach (native)
    at copyFiles (/usr/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:126:15)
    at module.exports.yeoman.generators.Base.extend.writing.writeBaseFiles (/usr/lib/node_modules/generator-jhipster-entity-audit/generators/app/index.js:147:12)
    at /usr/lib/node_modules/generator-jhipster-entity-audit/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
vagrant@vagrant-ubuntu-trusty-64:~/git/latestrsid$

**Comment by deepu105** [comment]
@srinisubra are you using the latest master branch of Jhipster? or is it Jhipster version 2.26.2? this module will work only with latest github master branch untill the next Jhipster release

from your trace it looks like you are using an installed Jhipster version and hence this is expected as the method is available in master branch,

**Comment by srinisubra** [comment]
Hi deepu105, I  just followed the local installation from here http://jhipster.github.io/installation.html and applied generator-jhipster-entity-audit and got the above error

**Comment by pascalgrimaud** [comment]
It's because the module generator-jhipster-entity-audit requires JHipster **v2.26.3** or **v2.27.0**, which is not out yet. You have 2 solutions :
- wait
- use the latest master branch of JHipster (like all JHipster contributors), as suggested by deepu

**Comment by srinisubra** [comment]
Thanks team. This got resolved by following your steps at https://github.com/deepu105/generator-jhipster-entity-audit/issues/2

Step1 : clone your fork deepu105/generator-jhipster, branch module-hook

mkdir -p ~/workspace/deepu
cd ~/workspace/deepu
git clone -b module-hook https://github.com/deepu105/generator-jhipster
cd generator-jhipster
npm install
npm link
ls -l /usr/lib/node_modules
Step2 : clone your module deepu105/generator-jhipster-entity-audit

cd ~/workspace/deepu
git clone https://github.com/deepu105/generator-jhipster-entity-audit
cd generator-jhipster-entity-audit
npm install
npm link
npm link generator-jhipster
ls -l node_modules
ls -l /usr/lib/node_modules
Step3 : create a sample project

cd ~/workspace/deepu
mkdir 01-mysql
cd 01-mysql
npm link generator-jhipster
yo jhipster
I answered to all questions, all by default

Step4 : launch your sub module

$ yo jhipster-entity-audit

**Comment by deepu105** [comment]
You can clone the jhipster master branch as well

**Comment by pascalgrimaud** [comment]
@srinisubra : I followed these steps because the deepu105's PR wasn't merge yet. Now it's merged, so you should :
- fork the main project generator-jhipster
- add remote to update your fork
- clone your fork and use it, instead of the branch module-hook
Try to follow https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by deepu105** [comment]
Thanks man
