### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by The-Crocop** [deepu105/generator-jhipster-entity-audit#6]
Hi just a short question. Does this generator work?
I tried out once and got an error. And on github it sais build failed?
Thanks in advance

**Comment by pascalgrimaud** [comment]
It's because the module generator-jhipster-entity-audit requires JHipster **v2.26.3** or **v2.27.0**, which is not out yet. You have 2 solutions :
- wait
- use the latest master branch of JHipster (like all JHipster contributors)

**Comment by deepu105** [comment]
Yes plz follow what pascal said above

**Comment by The-Crocop** [comment]
All Right thank you guys for the quick answer :)
