### ISSUE TITLE
Error: Cannot find module 'path-exists'

### ISSUE THREAD

**Issue by lsgpimentel** [deepu105/generator-jhipster-entity-audit#8]
After start using the master branch of `generator-jhipster` and `generator-jhipster-entity-audit`, the error below is generated when I `yo jhipster-entity-audit`.

```
Error: Cannot find module 'path-exists'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/delta/coding/generator-jhipster-entity-audit/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/base.js:19:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

Node version: v5.3.0

**Comment by deepu105** [comment]
Can you try with an LTS version of node what is the npm version you use.
This looks like an environment issue

**Comment by lsgpimentel** [comment]
In jhipster devbox (with Node v4.2.4 and npm v3.5.3), using jhipster master branche, I'm receiving the `TypeError: jhipsterFunc.copyTemplate is not a function` (no idea why, since I'm using the latest version).

I tried updating to npm v3.5.3 in my local environment, since I was using v3.2, and after the update the error changed to the same one in the dev box (`TypeError: jhipsterFunc.copyTemplate is not a function`). Very awkward :confused: 

Can you reproduce this in the devbox?

**Comment by deepu105** [comment]
Its available in the jhipster master branch only, did you do npm link on
the master branch?

**Comment by lsgpimentel** [comment]
Yes. I know. I'm using the master branch of both projects.

Could you reproduce this in the devbox?

**Comment by pascalgrimaud** [comment]
It's clearly a problem with npm link
Can you read this https://github.com/deepu105/generator-jhipster-entity-audit/issues/2 and try ?

I don't see any fork in your profile, so I suppose you clone directly project.
1) into your generator-jhipster folder : npm link
2) into your generator-jhipster-audit folder, there are 2 npm link to do : npm link, npm link generator-jhipster
3) into your app folder: npm link generator-jhipster

**Comment by lsgpimentel** [comment]
Thank you! That solved the problem.

Don't know why, but the `createdBy` field is not getting filled anymore - resulting in an validation error -, but that's another problem.

**Comment by deepu105** [comment]
createdBy is filled in an angular interceptor to avoid validation , check
if the interceptor is added during generation

Thanks & Regards,
Deepu

**Comment by lsgpimentel** [comment]
@deepu105, right you are again.

Sorry for extending the topic, but this don't make any sense to me.
The auditing fields are auto-filled by spring, so why resend it? This clearly impose a security problem, since I can override the fields in the client-side (in this case, `@JsonIgnore` should be placed in all auditing fields too).
These fields don't need Bean Validation. Not NULL in the database is more than enough.

If you want I can submit a pull request for this later.

**Comment by deepu105** [comment]
Yes if you can fix it plz PR. I also didn't want the interceptor but bean
validation was killing me
